### ISSUE TITLE
Can't find the training data used in the research paper

### ISSUE THREAD

**Issue by Yassinelaadraoui** [zshicode/Attention-CLX-stock-prediction#10]
Hey Shi, sorry for opening an issue but i couldn't text you directly, i'm interested in your research and i couldn't find the data used for this model since the website that you linked to is in chinese  and i couldn't understand
could you please send me the direct link for the data or an excel version 

thank you in advance

**Comment by zshicode** [comment]
You can run the example data 601988.SH.csv in this repo, and organize your data as a form like this CSV for your own usage.

**Comment by Yassinelaadraoui** [comment]
thanks for the quick reply, is there a way we can connect through twitter or any social network, i would love to pick your brain about this model
