### ISSUE TITLE
What is K in the source code?

### ISSUE THREAD

**Issue by songhappy** [zshicode/Attention-CLX-stock-prediction#14]
what is K in here?
        a = Lambda(lambda x: K.mean(x, axis=1), name='dim_reduction')(a)

https://github.com/zshicode/Attention-CLX-stock-prediction/blob/37c471ee207f9f9c2248672f0e4ca03136ddad0c/model.py#LL12C1-L23C1

**Comment by zshicode** [comment]
This operation is to obtain the mean value vector of tensor a. K is Keras.
