### ISSUE TITLE
Discussion: How to use this ML model on other market

### ISSUE THREAD

**Issue by josephgiting** [zshicode/Attention-CLX-stock-prediction#21]
This is not to report an issue with this project; but rather a discussion on how to use this model on other financial instruments.
This was a great research! Well done.
It looks possible to port this model on to other financial instruments; e.g. Forex, Indexes, Bonds, Futures etc. 
Would hope to know how would you suggest to tune/improve/change/test this ML model please?
Many thanks.

**Comment by zshicode** [comment]
In my opinion, the key to applying this model to other financial instruments and improving the performance, lies not only in the design of the algorithm, but also in the understanding of the data itself. Certainly, some of the techniques commonly used in deep learning, such as tuning the learning rate or dimensions of hidden layers, are likely to help improve the performance of the model.

**Comment by josephgiting** [comment]
Many thanks @zshicode for your speedy response.

I manage to run ARIMA.py, LSTM.py. However, when running Main.py, there is the following issue:

> 
> `File ~/workspace/Attention-based CNN-LSTM and XGBoost hybrid model for stock prediction/model.py:29, in attention_3d_block(inputs, single_attention_vector)
>      27 def attention_3d_block(inputs, single_attention_vector=False):
>      28     # inputs.shape = (batch_size, time_steps, input_dim)
> ---> 29     time_steps = K.int_shape(inputs)[1]
>      30     input_dim = K.int_shape(inputs)[2]
>      31     a = Permute((2, 1))(inputs)
> 
> NameError: name 'K' is not defined`

Would you please help?
Many thanks.

**Comment by josephgiting** [comment]
> Many thanks @zshicode for your speedy response.
> 
> I manage to run ARIMA.py, LSTM.py. However, when running Main.py, there is the following issue:
> 
> > `File ~/workspace/Attention-based CNN-LSTM and XGBoost hybrid model for stock prediction/model.py:29, in attention_3d_block(inputs, single_attention_vector)
> > 27 def attention_3d_block(inputs, single_attention_vector=False):
> > 28     # inputs.shape = (batch_size, time_steps, input_dim)
> > ---> 29     time_steps = K.int_shape(inputs)[1]
> > 30     input_dim = K.int_shape(inputs)[2]
> > 31     a = Permute((2, 1))(inputs)
> > NameError: name 'K' is not defined`
> 
> Would you please help? Many thanks.

Manage to fix it by adding the following line in model.py:

_import keras.backend as K_

 Cheers,
