### ISSUE TITLE
ARIMA_residuals1.csv

### ISSUE THREAD

**Issue by Damonququ** [zshicode/Attention-CLX-stock-prediction#25]
File "D:\installsoft\anaconda3\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './ARIMA_residuals1.csv'

没有这个文件啊

**Comment by zshicode** [comment]
首先，运行`ARIMA.py`进行ARIMA模型预处理步骤。然后：
- 运行`LSTM.py`，可使用单层LSTM、多层LSTM和双向LSTM模型。
- 运行`XGBoost.py`，可使用XGBoost模型。
- 运行`Main.py`，可使用我们提出的基于注意力的CNN-LSTM和XGBoost混合模型。
